commands: [
    ["surf", "srf metager.org", "S"],
    ["thor", "thorium",         "T"],
    ["file", "pcmanfm",         "F"],
    ["edit", "kitty nvim",      "E"],
    ["htop", "kitty htop",      "H"],
]

font-size: 24
font-path: "/home/ren/.local/share/fonts/Unknown Vendor/TrueType/Fira Mono/Fira_Mono_Regular.ttf"

exit-on-key: 1
window-width: 480
spacing: 6

background-color:  "#1E1E2E"
text-color:        "#BAC2DE"
command-color:     "#585B70"
key-color:         "#F38BA8"
